### ISSUE TITLE
Using bidi mixin in a block already targeting html root element fails

### ISSUE THREAD

**Issue by janbrasna** [mozilla/protocol#1008]
## Description

Since the `bidi()` prepends `[dir=rtl]␣`  it means it will produce `[dir=rtl] .class` but it's hard to achieve `.class[dir=rtl]` in case the selector/block starts with state classes applied to the `html` element itself; which is also the element with the `dir` attr.

### Steps to reproduce

SCSS:
``` scss
.ios {
    @media #{$mq-lg} {
        .mzp-c-split-body {
            @include bidi(((background, green, red),));
        }
    }
}

```
### Expected result

Red background applied in RTL languages.

### Actual result

output CSS:
```css
@media (min-width: 1024px) {
  .ios .mzp-c-split-body {
    background: green;
  }
  [dir=rtl] .ios .mzp-c-split-body {
    background: red;
  }
}
```

However the `[dir=rtl] .ios` here would need to be `.ios[dir=rtl]` for it to function.

Maybe a known limitation, just raising for some 👀 awareness…
