### ISSUE TITLE
input element shows repeating background on hover when disabled is true

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/protocol#767]
## Description

input element shows repeating background image of the search icon when disabled is set

### Steps to reproduce

go to https://mozilla.github.io/perfcompare/
edit HTML of search input element, add `disabled`
hover over search bar

![image](https://user-images.githubusercontent.com/18633586/153495308-5dd44fe5-65d9-4add-a738-c13af896ee13.png)

### Expected result
would expect search bar to look normal except gray text and icon

### Actual result
repeating background of search icon

### Environment

firefox release, ubuntu 18

**Comment by avi5079** [comment]
Hey @craigcook , @kimberlythegeek So I am working on this issue and I think I have fixed the issue but I don't know by changing scss file on protocol how it will reflect the change on perfcompare repo.
Could you please guide me for that?

**Comment by craigcook** [comment]
Feel free to submit a pull request with your fix. Once a fix is merged we'll need to publish a new version of Protocol to NPM, and the perf comparison site can then update their dependency to get the latest CSS.

**Comment by avi5079** [comment]
Hey @craigcook , So I added this code in the `_forms.scss` file in `input[type='search']` selector, but it is showing error in the terminal, can you guide me how to fix this error?

```scss
    &:disabled {
        background-image: $url-image-search-form;
        background-repeat: no-repeat;
        background-position: left 8px top 50%;
        padding: $field-padding $field-padding $field-padding
            calc(1.5em + #{$field-padding * 2});
        &:hover {
            background-image: $url-image-search-form;
        }
    }
```

Terminal error : 
![error](https://user-images.githubusercontent.com/102278822/161699982-7b10ffc0-c1c1-4efa-ac96-95289d39f135.PNG)
